version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: scripts/server_validate.sh
      timeout: 60
      runas: ec2-user